# Generated by Django 4.0.3 on 2022-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_lastname_alter_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
