# Generated by Django 4.0.3 on 2023-11-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groupId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='introducer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
