# Generated by Django 4.0.3 on 2023-11-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='branch',
            new_name='branchId',
        ),
    ]
