# Generated by Django 4.0.3 on 2023-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_branch_newuser_branchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='serialize_user_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
