# Generated by Django 4.0.3 on 2022-04-11 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyTitle', models.CharField(choices=[('Freehold', 'Freehold'), ('Leasehold', 'Leasehold')], default='Freehold', max_length=50)),
                ('saleType', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('rentalDeposit', models.CharField(max_length=50, null=True, verbose_name='Rental Deposit')),
                ('tenure', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('floorRange', models.IntegerField()),
                ('furnishing', models.CharField(choices=[('Freehold', 'Fully Furnish'), ('Partial', 'Partial Furnish'), ('None', 'None')], default='None', max_length=50)),
                ('amenities', models.CharField(max_length=200, null=True)),
                ('carpark', models.IntegerField()),
                ('otherInfo', models.CharField(max_length=255, null=True)),
                ('featureImage', models.ImageField(default='inventories/featured.jpg', upload_to=inventory.models.get_upload_path, verbose_name='Featured Image')),
                ('photo_1', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_2', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_3', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_4', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_5', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_6', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_7', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_8', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_9', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('photo_10', models.ImageField(blank=True, upload_to=inventory.models.get_upload_path)),
                ('video', models.URLField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('inventory_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='inventory.category')),
                ('propertyType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.propertytype')),
            ],
        ),
    ]
