# Generated by Django 4.0.3 on 2022-08-11 14:24

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path, verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_10',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path),
        ),
    ]
