# Generated by Django 4.0.6 on 2022-08-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_lastname_alter_profile_nickname_and_more'),
        ('inventory', '0004_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='profiles.profile'),
        ),
    ]
