# Generated by Django 4.0.6 on 2022-08-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user_name',
        ),
    ]
