# Generated by Django 4.0.3 on 2022-08-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_featureimage_alter_inventory_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='furnishing',
            field=models.CharField(choices=[('Fully furnish', 'Fully Furnish'), ('Partial', 'Partial Furnish'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='propertyTitle',
            field=models.CharField(choices=[('Strata', 'Strata'), ('Land', 'Land')], default='Strata', max_length=50),
        ),
    ]
