# Generated by Django 4.0.3 on 2022-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_furnishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='floorRange',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
