# Generated by Django 4.0.3 on 2022-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_size_alter_inventory_floorrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
