# Generated by Django 4.0.3 on 2022-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_user_name'),
        ('inventory', '0008_alter_inventory_state'),
    ]

    operations = [
    ]
