# Generated by Django 4.0.3 on 2022-10-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_merge_20221006_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
